/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import conexionSQL.ConexionSQL;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author JHON.CHAVEZ
 */
public class transporte extends javax.swing.JFrame {
    
    ConexionSQL cc = new ConexionSQL();
    Connection con =cc.Conexion();
    
    
    int filaSeleccionada;
//    int columnSeleccionada;
    
    public transporte() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        mostrarAuto();
        mostrarConductores();
        mostrarCliente();
        mostrarRuta();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        tablaRuta = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        btnNuevoAuto = new javax.swing.JButton();
        btnActualizarAuto = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaAutomovil = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaConductor = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        btnNuevoRuta = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaAutomovil1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevoAuto.setBackground(new java.awt.Color(0, 204, 51));
        btnNuevoAuto.setText("Nuevo");
        btnNuevoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAutoActionPerformed(evt);
            }
        });

        btnActualizarAuto.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarAuto.setText("Actualizar");
        btnActualizarAuto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnActualizarAutoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnActualizarAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarAutoMouseClicked(evt);
            }
        });
        btnActualizarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAutoActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 51, 51));
        jButton18.setText("Eliminar");

        tablaAutomovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Auto", "Placa", "Marca", "Modelo", "Color"
            }
        ));
        tablaAutomovil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAutomovilMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaAutomovil);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoAuto)
                .addGap(38, 38, 38)
                .addComponent(btnActualizarAuto)
                .addGap(30, 30, 30)
                .addComponent(jButton18)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton18)
                    .addComponent(btnActualizarAuto)
                    .addComponent(btnNuevoAuto))
                .addGap(33, 33, 33))
        );

        tablaRuta.addTab("Automovil", jPanel6);

        jButton19.setBackground(new java.awt.Color(0, 204, 51));
        jButton19.setText("Nuevo");

        jButton20.setBackground(new java.awt.Color(0, 153, 255));
        jButton20.setText("Actualizar");
        jButton20.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton20AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton21.setBackground(new java.awt.Color(255, 51, 51));
        jButton21.setText("Eliminar");

        tablaConductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Licencia", "Fecha Nacimienrto", "Direccion", "Telefono", "Correo", "Auto"
            }
        ));
        jScrollPane8.setViewportView(tablaConductor);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton19)
                .addGap(38, 38, 38)
                .addComponent(jButton20)
                .addGap(30, 30, 30)
                .addComponent(jButton21)
                .addGap(19, 19, 19))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton20)
                    .addComponent(jButton19))
                .addGap(33, 33, 33))
        );

        tablaRuta.addTab("Conductor", jPanel7);

        btnNuevoCliente.setBackground(new java.awt.Color(0, 204, 51));
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(0, 153, 255));
        jButton23.setText("Actualizar");
        jButton23.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton23AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton24.setBackground(new java.awt.Color(255, 51, 51));
        jButton24.setText("Eliminar");

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Apellido", "Telefono", "direccion", "Correo"
            }
        ));
        jScrollPane9.setViewportView(tablaCliente);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoCliente)
                .addGap(38, 38, 38)
                .addComponent(jButton23)
                .addGap(30, 30, 30)
                .addComponent(jButton24)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24)
                    .addComponent(jButton23)
                    .addComponent(btnNuevoCliente))
                .addGap(33, 33, 33))
        );

        tablaRuta.addTab("Cliente", jPanel8);

        btnNuevoRuta.setBackground(new java.awt.Color(0, 204, 51));
        btnNuevoRuta.setText("Nuevo");
        btnNuevoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRutaActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(0, 153, 255));
        jButton26.setText("Actualizar");
        jButton26.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton26AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton27.setBackground(new java.awt.Color(255, 51, 51));
        jButton27.setText("Eliminar");

        tablaAutomovil1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. Ruta", "Conductor", "Automovil", "Origen", "Destino"
            }
        ));
        jScrollPane10.setViewportView(tablaAutomovil1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoRuta)
                .addGap(38, 38, 38)
                .addComponent(jButton26)
                .addGap(30, 30, 30)
                .addComponent(jButton27)
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton27)
                    .addComponent(jButton26)
                    .addComponent(btnNuevoRuta))
                .addGap(33, 33, 33))
        );

        tablaRuta.addTab("Ruta", jPanel9);

        jTabbedPane2.addTab("taxi", tablaRuta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarAutoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnActualizarAutoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarAutoAncestorAdded

    private void jButton20AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton20AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20AncestorAdded

    private void jButton23AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton23AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23AncestorAdded

    private void jButton26AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton26AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26AncestorAdded

    private void btnNuevoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRutaActionPerformed
        //NewAuto nuevoAuto = new  NewAuto();
        //nuevoAuto.setVisible(true);
    }//GEN-LAST:event_btnNuevoRutaActionPerformed

    private void btnNuevoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAutoActionPerformed
        NewAuto nuevoAuto = new  NewAuto();
        nuevoAuto.setVisible(true);
        nuevoAuto.btnModificarAuto.setVisible(false);
    }//GEN-LAST:event_btnNuevoAutoActionPerformed

    private void tablaAutomovilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAutomovilMouseClicked
        filaSeleccionada = tablaAutomovil.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tablaAutomovilMouseClicked

    private void btnActualizarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAutoActionPerformed

        NewAuto na = new  NewAuto();
        int fila = tablaAutomovil.getSelectedRow();
        
        NewAuto.txtPlaca.setText(tablaAutomovil.getValueAt(fila, 1).toString());
        NewAuto.txtMarcaA.setText(tablaAutomovil.getValueAt(fila, 2).toString());
        NewAuto.txtModeloA.setText(tablaAutomovil.getValueAt(fila, 3).toString());
        NewAuto.txtColorA.setText(tablaAutomovil.getValueAt(fila, 4).toString());
        NewAuto.id_auto=Integer.parseInt(tablaAutomovil.getValueAt(fila, 0).toString());
        NewAuto.btnInsertar.setVisible(false);
       
        
        na.setVisible(true);
    }//GEN-LAST:event_btnActualizarAutoActionPerformed

  
    
    
    
    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        NewCliente nuevoCliente = new  NewCliente();
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnActualizarAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarAutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarAutoMouseClicked

    public void mostrarAuto(){
        String[] titulos = {"ID", "Placa","Marca", "Modelo","Color"};
        String [] registros = new String[6];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM automovil";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("id_auto");
                registros[1]=rs.getString("placa");
                registros[2]=rs.getString("marca");
                registros[3]=rs.getString("modelo");
                registros[4]=rs.getString("color");
                
                modelo.addRow(registros);
            }
            tablaAutomovil.setModel(modelo);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
        
    }
    
    
    public void mostrarConductores(){
        String[] titulos = {"Documento", "Nombre","Apellido", "Licencia","Nacimiento","Telefono","Direccion","Correo","No. Auto"};
        String [] registros = new String[9];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM conductor";
    
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("documento");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("licencia");
                registros[4]=rs.getString("fecha_nacimiento");
                registros[5]=rs.getString("telefono");
                registros[6]=rs.getString("direccion");
                registros[7]=rs.getString("correo");
                registros[8]=rs.getString("fk_idauto");
                
                modelo.addRow(registros);
            }
            tablaConductor.setModel(modelo);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
    }
    
    
    public void mostrarCliente(){
        String[] titulos = {"Documento", "Nombre","Apellido", "Telefono","Direccion","Correo"};
        String [] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM cliente";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("documento");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("telefono");
                registros[4]=rs.getString("direccion");
                registros[5]=rs.getString("correo");
                
                modelo.addRow(registros);
            }
            tablaCliente.setModel(modelo);
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
    }
    
    
    public void mostrarRuta(){
        String[] titulos = {"ID", "Nombre","Apellido", "Telefono","Direcciom","Email"};
        String [] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM ruta";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("documento");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("telefono");
                registros[4]=rs.getString("direccion");
                registros[5]=rs.getString("correo");
                
                modelo.addRow(registros);
            }
            tablaCliente.setModel(modelo);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAuto;
    private javax.swing.JButton btnNuevoAuto;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoRuta;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tablaAutomovil;
    private javax.swing.JTable tablaAutomovil1;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaConductor;
    private javax.swing.JTabbedPane tablaRuta;
    // End of variables declaration//GEN-END:variables
}
